name: Publish

on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - name: Set up identity
        run: |
          git config --local user.email "jonasz.wiacek@softwarebrothers.co"
          git config --local user.name "Firebase AdminBro"
      - run: yarn publish --new-version ${GITHUB_REF##*/}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
